# Generated by Django 5.2.6 on 2026-02-07 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_categorie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('agent', 'Agent'), ('manager', 'Manager'), ('bailleur', 'Bailleur')], max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bien', models.CharField(choices=[('villa', 'Villa'), ('appartement', 'Appartement'), ('terrain', 'Terrain'), ('bureau', 'Bureau')], max_length=50)),
                ('option', models.CharField(choices=[('vente', 'Vente'), ('location', 'Location')], max_length=10)),
                ('adresse', models.CharField(max_length=255)),
                ('surface', models.FloatField()),
                ('nombre_piece', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_proprietes/')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietes_agent', to=settings.AUTH_USER_MODEL)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietes_bailleur', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SE.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SE.propriete')),
            ],
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SE.propriete')),
            ],
            options={
                'unique_together': {('client', 'propriete')},
            },
        ),
    ]
