# Generated by Django 5.2.6 on 2026-02-17 22:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favori',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
